### ISSUE TITLE
Verify working with 3.4 NVR version

### ISSUE THREAD

**Issue by socalracer** [kk7ds/uvcclient#2]
I am using HomeAssistant and one of the dependencies is uvcclient 0.9.0. It seems a bunch of people have had problems with the API in the new Ubiquiti NVR version 3.4. Can you verify this is working in 3.4?

**Comment by kk7ds** [comment]
I'm running 3.2 and it works fine, haven't tried 3.4. They did break the API between 3.1 and 3.2 in a completely incompatible way, so I guess I shouldn't be surprised if they did it again...

**Comment by socalracer** [comment]
Any update on this?

**Comment by kk7ds** [comment]
I'm still using this in 3.7 without any problems so I'm assuming this is resolved. Re-open and let me know if not.
