### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by carlos-sarmiento** [kk7ds/uvcclient#4]
The library seems not to work if configured to access an HTTPS endpoint. My python is not particularly good, but I never saw a mention of HTTPSConnection on nvr.py.

Would you be interested in a pull request adding the support?

**Comment by kk7ds** [comment]
Sure :)

**Comment by carlos-sarmiento** [comment]
I created the PR :)

**Comment by carlos-sarmiento** [comment]
Closed since PR landed
